import type { HazardContent } from '@/lib/db/types'

export type BuiltInHazard = HazardContent & {
  /** Stable key (never stored). */
  key: string
}

/**
 * Built-in hazards offered under "Add hazard". Content fields are multi-line: one risk /
 * outcome / control measure per line.
 */
export const BUILT_IN_HAZARDS: readonly BuiltInHazard[] = [
  {
    key: 'manual-handling',
    name: 'Manual Handling',
    description:
      'Lifting, carrying, pushing, pulling or lowering equipment, props, set pieces and kit during load-in, shoot and wrap.',
    risks: [
      'Musculoskeletal injury (back, shoulder, neck, limbs) from lifting or carrying heavy, awkward or bulky items.',
      'Trips, slips and dropped loads causing crush, impact or trapping injuries.',
    ].join('\n'),
    outcomes: 'Strains and sprains, long-term back injury, cuts, bruising, broken bones.',
    control_measures: [
      'Assess each load (weight, size, route, destination) before moving it; do not lift if unsure.',
      'Use trolleys, sack barrows, carts or lifting aids wherever possible.',
      'Team-lift heavy or awkward items with clear communication; one person leads the lift.',
      'Keep walkways and loading routes clear, dry and well lit.',
      'Wear suitable footwear and gloves; use correct lifting technique (bend knees, keep the load close).',
      'Take regular breaks and rotate crew on repetitive handling tasks; report any injury to the first aider immediately.',
    ].join('\n'),
    at_risk_crew: 1,
    at_risk_cast: 0,
    at_risk_public: 0,
    severity_before: 4,
    probability_before: 3,
    severity_after: 2,
    probability_after: 2,
  },
  {
    key: 'drone-flying',
    name: 'Flying Drones (Internal and External)',
    description:
      'Flying drones indoors and outdoors in the designated filming spaces, by licensed operators working with all involved personnel.',
    risks: [
      'Collisions with people and property (tree branches, power lines, warehouse racking and machinery).',
      'Loss of control owing to loss of GPS connection.',
    ].join('\n'),
    outcomes: 'Serious injury to people, damage to property and equipment, loss of the drone.',
    control_measures: [
      'Drones will only be flown by competent licensed operators in line with CAA regulations and UK law.',
      'All personnel will be kept clear of designated take-off and landing zones.',
      'Visual line of sight will be maintained with the drone at all times by either the pilot or a designated spotter.',
      'All movements will be broken down step by step and coordinated with on-site personnel before filming.',
      'Drones will maintain a minimum distance of 5m above all personnel at all times.',
      'If loss of GPS connection occurs and it becomes clear that control of drones cannot be maintained, all drone operation will cease.',
    ].join('\n'),
    at_risk_crew: 1,
    at_risk_cast: 1,
    at_risk_public: 0,
    severity_before: 5,
    probability_before: 3,
    severity_after: 4,
    probability_after: 1,
  },
  {
    key: 'trip-hazards',
    name: 'Trip Hazards',
    description: 'Trailing cables, props, bags, camera equipment and uneven terrain around the filming area.',
    risks: 'Trips and falls resulting in strain or sprain injuries, broken bones, or death.',
    outcomes: 'Strains and sprains, broken bones, death.',
    control_measures: [
      'Plan and lay out the environment carefully.',
      'Tape and secure all cables to avoid trip hazards.',
      'Ensure lighting is adequate to highlight objects and obstacles.',
      'Mark out the area being filmed and ensure only authorised persons are permitted into the area to minimise the risks.',
      'Ensure cast and crew are aware of any obstacles.',
    ].join('\n'),
    at_risk_crew: 1,
    at_risk_cast: 1,
    at_risk_public: 0,
    severity_before: 4,
    probability_before: 3,
    severity_after: 4,
    probability_after: 1,
  },
  {
    key: 'lighting',
    name: 'Lighting',
    description:
      'Lights can become very hot in use, can be very bright and disorientate or hide obstacles, and can fall from rigs if not secured correctly.',
    risks: [
      'Handling hot lights could result in burns or fire.',
      'Position of lights could result in blind-spots, which could result in fall of stage or over objects.',
      'Falling lights could result in impact and head injuries.',
    ].join('\n'),
    outcomes: 'Burns, fire, trips and falls, impact and head injuries.',
    control_measures: [
      'Always use the breaker switches provided with the kit.',
      'Always wear gloves when handling lights; ensure lights are switched off and allowed to cool before being handled or moved.',
      'Always position lights away from combustible or flammable items to prevent fire.',
      'Plan the lighting pattern and check for blind-spots during set up.',
      'Warn cast and crew and point lights away from faces before lights are switched on.',
      'Never daisy chain extension leads or use lights near water or outside.',
      'Ensure lights are fastened securely by competent persons and appropriate safety fixtures are in place.',
      'Tape down the length of each cable (bring your own gaffer tape).',
      'Never use lights in a public place unless each light stand has a person standing beside and holding the stand.',
      "Check the location's electricity ring mains can supply the necessary power for the lights being used.",
    ].join('\n'),
    at_risk_crew: 1,
    at_risk_cast: 1,
    at_risk_public: 0,
    severity_before: 5,
    probability_before: 2,
    severity_after: 5,
    probability_after: 1,
  },
  {
    key: 'access-egress-blocking',
    name: 'Access / Egress Blocking',
    description: 'Blocking of entrances and exits whilst filming takes place.',
    risks: [
      'Delayed escape in an emergency could result in people being trapped by fire.',
      'Delayed access by emergency services could result in injuries becoming more severe.',
    ].join('\n'),
    outcomes: 'People trapped by fire, injuries becoming more severe, death.',
    control_measures: [
      'Maintain clear routes into and out of the filming area at all times.',
      'Where this is not possible, have a clear procedure of action to take in an emergency, such as a fire alarm sounding or someone needing medical help.',
    ].join('\n'),
    at_risk_crew: 1,
    at_risk_cast: 1,
    at_risk_public: 1,
    severity_before: 5,
    probability_before: 2,
    severity_after: 5,
    probability_after: 1,
  },
  {
    key: 'personal-security',
    name: 'Personal Security',
    description: 'Carrying or using expensive equipment.',
    risks: 'Carrying or using expensive equipment could increase the likelihood of personal attack, which could result in life threatening injuries.',
    outcomes: 'Life threatening injuries.',
    control_measures: [
      'If working in a location where you may be at risk of theft, ensure no lone working.',
      'Carry a mobile phone or have the means of contacting emergency services.',
      'Keep equipment out of sight in vehicles when travelling to and from location.',
    ].join('\n'),
    at_risk_crew: 1,
    at_risk_cast: 0,
    at_risk_public: 0,
    severity_before: 5,
    probability_before: 3,
    severity_after: 5,
    probability_after: 1,
  },
  {
    key: 'fatigue',
    name: 'Crew and Contributor Fatigue',
    description: 'Working excessive hours or not taking adequate breaks.',
    risks: 'Excessive fatigue, dehydration and poor concentration resulting in accidents.',
    outcomes: 'Accidents and injuries caused by tiredness and loss of concentration.',
    control_measures: [
      'Ensure adequate breaks are planned.',
      'Ensure food and drinks are available to crew and contributors.',
    ].join('\n'),
    at_risk_crew: 1,
    at_risk_cast: 1,
    at_risk_public: 0,
    severity_before: 3,
    probability_before: 2,
    severity_after: 3,
    probability_after: 1,
  },
  {
    key: 'theft',
    name: 'Theft of Equipment and Personal Possessions',
    description: "Being in public with expensive camera equipment; crew and cast's personal possessions may be on-site.",
    risks: 'Risk of theft.',
    outcomes: 'Loss of equipment and personal possessions; confrontation with thieves.',
    control_measures: [
      'Keep personal items stored in a locked vehicle or in close proximity to crew members.',
      'Keep track of all equipment and bags at all times.',
      'Keep a mobile phone on all crew members at all times to facilitate quick contact of emergency services if necessary.',
    ].join('\n'),
    at_risk_crew: 1,
    at_risk_cast: 1,
    at_risk_public: 0,
    severity_before: 3,
    probability_before: 2,
    severity_after: 3,
    probability_after: 1,
  },
  {
    key: 'smoking',
    name: 'Smoking on Set',
    description: 'Smoking during filming by cast or contributors.',
    risks: [
      'Fire if a cigarette is carelessly discarded.',
      'Passive smoke inhalation by other cast, crew and filming members.',
    ].join('\n'),
    outcomes: 'Fire, burns, smoke inhalation.',
    control_measures: [
      'Avoid use of conventional cigarettes wherever possible; where not possible, limit use of cigarettes to an absolute minimum.',
      'Do not permit smoking other than during filming.',
      'Provide an appropriate receptacle for disposal of cigarette butts to avoid risk of fire.',
      'Keep persons present to a minimum.',
      'If in a confined space or on a flammable set, make sure there is a fire extinguisher or fire blanket or water in case of emergency.',
    ].join('\n'),
    at_risk_crew: 1,
    at_risk_cast: 1,
    at_risk_public: 1,
    severity_before: 4,
    probability_before: 2,
    severity_after: 4,
    probability_after: 1,
  },
  {
    key: 'stunts',
    name: 'Stunts',
    description: 'Specialist stunts being filmed, which could go wrong.',
    risks: 'The unusual nature of stunts could present a multitude of significant risks and serious injuries or death if not planned properly.',
    outcomes: 'Serious injuries, death.',
    control_measures: [
      'Always seek advice from a competent person.',
      'Stunts are only performed by qualified stunt performers under the direction of a stunt coordinator.',
      'Each stunt has its own specific risk assessment, agreed with the director, 1st AD and relevant heads of department before the shoot.',
      'Rehearse and walk through each stunt, and check rigs, equipment, landing areas and vehicles before every take.',
      'Keep a clear safety zone around the stunt area and only essential personnel present; everyone else stays at a safe distance.',
      'Brief everyone involved on each stunt, agree start and abort signals, and allow anyone to stop a stunt they believe is unsafe.',
      'Do not perform a stunt if the weather, surface or lighting conditions are unsafe.',
      'Have a qualified first aider or medic on standby.',
      'Have a detailed emergency action plan in place, which includes how emergency services will be summoned.',
    ].join('\n'),
    at_risk_crew: 0,
    at_risk_cast: 1,
    at_risk_public: 0,
    severity_before: 5,
    probability_before: 2,
    severity_after: 5,
    probability_after: 1,
  },
  {
    key: 'electrical-equipment',
    name: 'Electrical Equipment',
    description: 'Poorly maintained or damaged equipment being used; overloading plug sockets; using incorrectly rated equipment in the wrong environment.',
    risks: 'Damaged or faulty electrical equipment, overloading or using the wrong equipment could result in electric shock, electrocution or fire.',
    outcomes: 'Electric shock, electrocution, fire, death.',
    control_measures: [
      'Ensure equipment is properly maintained and regularly inspected.',
      'Never overload sockets and monitor this on location.',
      'Choose 110v equipment where possible and ensure intrinsic protection in high risk environments.',
      'Never use electrical equipment in wet environments except those of a suitable IP rating; ask a competent electrician to advise.',
    ].join('\n'),
    at_risk_crew: 1,
    at_risk_cast: 0,
    at_risk_public: 0,
    severity_before: 4,
    probability_before: 2,
    severity_after: 4,
    probability_after: 1,
  },
  {
    key: 'vehicles',
    name: 'Vehicles',
    description: 'Cast or crew could be struck by a moving vehicle on set or being filmed.',
    risks: 'Crushing or impact injuries could result in disabling injury or death.',
    outcomes: 'Disabling injury, death.',
    control_measures: [
      'Limit vehicle movement wherever possible.',
      'Where vehicle movement is being filmed, ensure no unnecessary people are in the vicinity.',
      'Always have a designated back-watcher to protect the camera operator from oncoming vehicles.',
      'If filming from a moving car, use a harness on the camera operator and camera to prevent sudden stop injuries and falling.',
      'Ensure the roadworthiness of the vehicle.',
      'Ensure competency and experience of the drivers.',
      'If filming from car to car, use walkie talkies to keep in contact with other vehicles.',
      'Ensure the licence plate is always visible.',
      'If filming on a public road, speak to the police first; filming on private land has fewer restrictions but safety comes first.',
    ].join('\n'),
    at_risk_crew: 1,
    at_risk_cast: 1,
    at_risk_public: 0,
    severity_before: 5,
    probability_before: 2,
    severity_after: 5,
    probability_after: 1,
  },
  {
    key: 'roads',
    name: 'Filming on Roads',
    description: 'Filming on roads, where people could be struck by moving vehicles or an obstruction could cause a road traffic accident.',
    risks: [
      'Crushing or impact injuries could result in disabling injury or death.',
      'Road traffic accident caused by an obstruction could result in multiple casualties and possible deaths.',
    ].join('\n'),
    outcomes: 'Disabling injury, multiple casualties, death.',
    control_measures: [
      'If filming in the carriageway, seek advice from a competent person (Chapter 8 qualified) as signing, lighting and guarding on the highway may be required.',
      'Always have a designated back-watcher to protect the camera operator from oncoming vehicles.',
    ].join('\n'),
    at_risk_crew: 1,
    at_risk_cast: 1,
    at_risk_public: 1,
    severity_before: 4,
    probability_before: 2,
    severity_after: 4,
    probability_after: 1,
  },
  {
    key: 'water',
    name: 'Working On or Near Water',
    description: 'Filming on or near water could result in people falling into it or being washed away.',
    risks: [
      'Falling into cold water could result in hypothermia and drowning.',
      'Being washed into rapid moving water could result in impact injuries, hypothermia and drowning.',
    ].join('\n'),
    outcomes: 'Impact injuries, hypothermia, drowning, Weil\'s disease.',
    control_measures: [
      'Always seek the advice of a competent person before working on or near water.',
      'Put a detailed emergency plan in place before filming starts, including the safety equipment and rescue methods.',
      "Inform crew of the potential risk from Weil's disease and tell them to contact their GP if flu-like illness, persistent severe headache, vomiting, muscle pains or jaundice develop.",
      'Maintain a 3m exclusion zone from the water\'s edge.',
      'Staff within the exclusion zone wear life jackets and/or a harness attached to a secured safety lanyard.',
    ].join('\n'),
    at_risk_crew: 1,
    at_risk_cast: 1,
    at_risk_public: 0,
    severity_before: 5,
    probability_before: 2,
    severity_after: 5,
    probability_after: 1,
  },
  {
    key: 'construction-sites',
    name: 'Building and Construction Sites',
    description: 'Contact with moving machinery or plant, falling objects from overhead works, open trenches and excavations.',
    risks: 'Building and construction sites present a multitude of risks which are unique to the particular site; many could result in serious or fatal injuries.',
    outcomes: 'Serious or fatal injuries.',
    control_measures: [
      'Always book into the site office of the building/construction site agent.',
      'Attend the site induction and follow the instructions you have been given by the site agent.',
      'Make sure personal protective equipment and clothing is available, and always wear any personal protective gear you have been given.',
    ].join('\n'),
    at_risk_crew: 1,
    at_risk_cast: 1,
    at_risk_public: 0,
    severity_before: 5,
    probability_before: 2,
    severity_after: 5,
    probability_after: 1,
  },
  {
    key: 'hostile-environment',
    name: 'Hostile Environment',
    description: 'A hostile environment may result in physical attack.',
    risks: 'Physical attack could result in life threatening injuries.',
    outcomes: 'Life threatening injuries.',
    control_measures: [
      'Always seek advice from competent persons before planning to visit a hostile environment.',
      'Check official government travel advice for the location.',
      'If you are an inexperienced traveller, travel with experienced travellers.',
      'Do not travel alone.',
    ].join('\n'),
    at_risk_crew: 1,
    at_risk_cast: 1,
    at_risk_public: 0,
    severity_before: 5,
    probability_before: 2,
    severity_after: 5,
    probability_after: 1,
  },
  {
    key: 'smoke-fx',
    name: 'Smoke FX',
    description: 'Generating smoke inside a building or outdoors.',
    risks: [
      'Could increase risk of asthma attack in susceptible individuals.',
      'Could obscure escape routes inside, causing panic and delayed escape in an emergency.',
      'Could cause false fire alarm activation inside.',
      'Could cause concern outside if observers think a fire is present.',
      'Could obscure vision on roads and footpaths, resulting in accidents.',
    ].join('\n'),
    outcomes: 'Asthma attacks, panic, delayed escape, accidents.',
    control_measures: [
      'Always seek advice and permission from the building owner before using inside a building.',
      'Always seek advice from a competent person before using outside and ensure they have their own risk assessment for the job.',
      'Have a team member outside at all times to communicate with and explain to concerned passers-by.',
      'Have a clear exit planned and make sure all cast and crew are aware of exit doors.',
    ].join('\n'),
    at_risk_crew: 1,
    at_risk_cast: 1,
    at_risk_public: 1,
    severity_before: 3,
    probability_before: 2,
    severity_after: 3,
    probability_after: 1,
  },
]

export function getBuiltInHazard(key: string): BuiltInHazard | undefined {
  return BUILT_IN_HAZARDS.find((h) => h.key === key)
}
