/**
 * Layout classifier for the Toothpick script PDF.
 *
 * Why this exists: Albatross's PDF parser anchors the action margin on the scene-heading line's x
 * position. In this script the headings start in the left scene-number gutter (x≈51pt) while action
 * text starts at x≈101pt, so the parser mis-detects the columns and labels every body line
 * "dialogue" (1,061 of 1,061 body lines). The page text stored for the Script Supervisor then has
 * no block structure, and each scene collapses to ~3 lines in the lined-script view.
 *
 * This classifier reads the same positioned lines (`extractPdfLines`) but derives the columns from
 * the body text itself, and numbers pages as printed (title page excluded). Its output replaces the
 * parser's `elements`; everything else about the script version is generated by the app's own code.
 */
import type { PdfLine, ScriptElement, PdfLineType } from '@/lib/script-parser'

export type LayoutScene = { sceneNumber: string; elements: ScriptElement[]; cues: string[]; firstPage: number; lastPage: number }

const HEADING = /^(\d+[A-Za-z]?)\s+(?:INT\.?\/EXT\.?|EXT\.?\/INT\.?|I\/E|INT|EXT)[\s.]/i
const DIRECTIVE = /^(CUT TO|SMASH CUT|WHIP PAN TO|FADE|DISSOLVE|MATCH CUT|MONTAGE:|SPLITSCREEN|PAUSE SPLITSCREEN)/i

type Columns = { action: number; dialogue: number; cue: number }

/** Derive the action / dialogue / cue columns from the body lines' left edges. */
export function detectColumns(lines: readonly PdfLine[]): Columns {
  const width = lines[0]?.pageWidth || 595
  const counts = new Map<number, number>()
  for (const l of lines) {
    if (HEADING.test(l.text) || l.x > width * 0.5) continue
    const k = Math.round(l.x)
    counts.set(k, (counts.get(k) ?? 0) + 1)
  }
  // Peaks with real support, ignoring the thin parenthetical column.
  const peaks = [...counts.entries()].filter(([, n]) => n >= 40).map(([x]) => x).sort((a, b) => a - b)
  if (peaks.length < 3) throw new Error(`Expected action, dialogue and cue columns; found ${JSON.stringify(peaks)}`)
  return { action: peaks[0]!, dialogue: peaks[1]!, cue: peaks[peaks.length - 1]! }
}

function isPageNumberHeader(l: PdfLine, topOfPage: PdfLine | undefined): boolean {
  return l === topOfPage && /^\d+[A-Za-z]?\.?$/.test(l.text)
}

export function classifyScript(lines: readonly PdfLine[]): LayoutScene[] {
  const cols = detectColumns(lines)
  const width = lines[0]?.pageWidth || 595
  const tol = 14

  // Top-most line per page (the printed page number lives there).
  const top = new Map<number, PdfLine>()
  for (const l of lines) if (!top.get(l.page) || l.y > top.get(l.page)!.y) top.set(l.page, l)

  const scenes: LayoutScene[] = []
  let current: LayoutScene | null = null

  for (const l of lines) {
    if (isPageNumberHeader(l, top.get(l.page))) continue
    const h = HEADING.exec(l.text)
    // Printed numbering: the title page is physical page 1 and unnumbered; script page 1 is physical 2.
    const printedPage = l.page - 1
    if (h && l.x < cols.action - 20) {
      current = { sceneNumber: h[1]!, elements: [], cues: [], firstPage: printedPage, lastPage: printedPage }
      scenes.push(current)
      // Drop the margin scene numbers so the Supervisor recognises the line as a heading ("INT. ...").
      const heading = l.text.replace(/^\d+[A-Za-z]?\s+/, '').replace(/\s+\d+[A-Za-z]?$/, '').replace(/\s+[–—]\s+/g, ' - ')
      current.elements.push({ type: 'scene_heading', text: heading, page: printedPage })
      continue
    }
    if (!current) continue // title page and anything before scene 1

    const text = l.text
    let type: PdfLineType
    if (l.x > width * 0.5 || DIRECTIVE.test(text)) type = 'transition'
    else if (text.startsWith('(')) type = 'parenthetical'
    else if (l.x >= cols.cue - tol) type = 'character'
    else if (l.x >= cols.dialogue - tol) type = 'dialogue'
    else type = 'action'

    if (type === 'character') {
      const name = text.replace(/\(.*?\)/g, '').trim()
      if (name && !current.cues.some((c) => c.toUpperCase() === name.toUpperCase())) current.cues.push(name)
    }
    current.elements.push({ type, text, page: printedPage })
    current.lastPage = printedPage
  }
  return scenes
}
