import type { TutorialFlow } from '../engine/types'

export const scheduleFlow: TutorialFlow = {
  sectionId: 'schedule',
  title: 'Schedule',
  route: '/schedule/shots',
  steps: [
    {
      id: 'shots-overview',
      title: 'Shots come first',
      body: 'Scenes come from your script. Shots are the individual setups within a scene, and they feed the stripboard.',
      instruction: 'Press Next when you are ready to add a shot.',
      requires: { kind: 'view' },
    },
    {
      id: 'add-scene',
      title: 'Create a scene',
      body: 'Scenes come from the script, and every shot belongs to one. This project starts with none, so create the first one.',
      instruction: 'Click New scene.',
      target: 'scene-new',
      hint: 'Click the highlighted New scene button.',
      requires: { kind: 'click' },
    },
    {
      id: 'save-scene',
      title: 'Save the scene',
      body: 'Enter a scene number and title, then save. The new scene becomes the one you are working on.',
      instruction: 'Fill in the form in the open dialog and save the scene.',
      requires: { kind: 'event', event: 'scene.created' },
      hint: 'Save the scene in the open dialog to continue.',
    },
    {
      id: 'add-shot',
      title: 'Add a shot',
      body: 'Shots are the individual setups within the scene you just created.',
      instruction: 'Click the Add shot button.',
      target: 'shot-add',
      hint: 'Click the highlighted Add shot button to open the form.',
      needs: ['scene'],
      requires: { kind: 'click' },
    },
    {
      id: 'save-shot',
      title: 'Save the shot',
      body: 'Choose a scene, enter a shot number and save. The tutorial notices the saved shot.',
      instruction: 'Fill in the form in the open dialog and click Add shot to save it.',
      requires: { kind: 'event', event: 'shot.created' },
      hint: 'Save the shot in the open dialog to continue.',
    },
    {
      id: 'stripboard-views',
      title: 'The stripboard',
      body: 'The stripboard lays shots out across shoot days. Board view shows columns you can drag between. Day view shows one day as a table.',
      instruction: 'The view switch is highlighted. Press Next to continue.',
      route: '/schedule/stripboard',
      view: { param: 'view', value: 'board' },
      target: 'stripboard-views',
      optional: true,
      requires: { kind: 'view' },
    },
    {
      id: 'new-day',
      title: 'Create a shoot day',
      body: 'Every strip goes on a shoot day. Create one for the first day of the shoot.',
      instruction: 'Click New shoot day.',
      route: '/schedule/stripboard',
      view: { param: 'view', value: 'board' },
      target: 'stripboard-new-day',
      hint: 'Click the highlighted New shoot day button.',
      requires: { kind: 'click' },
    },
    {
      id: 'save-day',
      title: 'Pick a date',
      body: 'Choose a date and save. The shoot day appears as a column.',
      instruction: 'Fill in the date in the open dialog and create the shoot day.',
      route: '/schedule/stripboard',
      view: { param: 'view', value: 'board' },
      requires: { kind: 'event', event: 'shootday.created' },
      hint: 'Create the shoot day in the open dialog to continue.',
    },
    {
      id: 'add-strip',
      title: 'Put a shot on the day',
      body: 'Add strip places a shot onto a shoot day. You can also drag strips between days.',
      instruction: 'Click Add strip.',
      route: '/schedule/stripboard',
      view: { param: 'view', value: 'board' },
      target: 'stripboard-add-strip',
      hint: 'Click the highlighted Add strip button.',
      needs: ['shot', 'shootDay'],
      requires: { kind: 'click' },
    },
    {
      id: 'save-strip',
      title: 'Choose a shot and a day',
      body: 'Pick the shot you created and the day you just made.',
      instruction: 'Choose the shot and day in the open panel, then add the strip.',
      route: '/schedule/stripboard',
      view: { param: 'view', value: 'board' },
      requires: { kind: 'event', event: 'stripboard.strip_added' },
      hint: 'Add the strip in the open panel to continue.',
    },
    {
      id: 'day-view',
      title: 'Day view',
      body: 'Day view shows one shoot day as a table, with a row for each strip. Use it to review a single day.',
      instruction: 'Press Next to look at the day view.',
      route: '/schedule/stripboard',
      view: { param: 'view', value: 'day' },
      target: 'stripboard-day-view',
      needs: ['shootDay'],
      optional: true,
      requires: { kind: 'view' },
    },
  ],
}
